# Generated by Django 3.1.4 on 2020-12-12 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='City',
            new_name='city',
        ),
    ]
