bedroom_choices = {
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5': 5,
    '6': 6,
    '7': 7,
    '8': 8,
    '9': 9,
    '10': 10
}

price_choices = {
    '100000': '$ 100000',
    '200000': '$ 200000',
    '300000': '$ 300000',
    '400000': '$ 400000',
    '500000': '$ 500000',
    '600000': '$ 600000',
    '700000': '$ 700000',
    '800000': '$ 800000',
    '900000': '$ 900000',
    '1000000': '$ 1M+',
}

state_choices = {
    'NM': 'New Mexico',
    'NY': 'New York',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'NJ': 'New Jersey',
    'AL': 'Alabama',
    'AK': 'Alaska',
    'WY': 'Wyoming',
    'WI': 'Wisconsin',
    'WV': 'West Virginia',
    'WA': 'Washington',
    'VA': 'Virginia',
    'VT': 'Vermont',
    'UT': 'Utah',
    'TX': 'Texas',
    'TN': 'Tennessee',
    'SD': 'South Dakota',
    'SC': 'South Carolina',
    'RI': 'Rhode Island',
    'PA': 'Pennsylvania',
    'OR': 'Oregon',
    'OK': 'Oklahoma',
    'OH': 'Ohio',
    'NH': 'New Hampshire',
    'NV': 'Nevada',
    'NE': 'Nebraska',
    'MT': 'Montana',
    'MO': 'Missouri',
    'MS': 'Mississippi',
    'MN': 'Minnesota',
    'MA': 'Massachusetts',
    'MD': 'Maryland',
    'ME': 'Maine',
    'LA': 'Louisiana',
    'KY': 'Kentucky',
    'KS': 'Kansas',
    'IA': 'Iowa',
    'IN': 'Indiana',
    'IL': 'Illinois',
    'ID': 'Idaho',
    'HI': 'Hawaii',
    'GA': 'Georgia',
    'FL': 'Florida',
    'DC': 'District Of Columbia',
    'DE': 'Delaware',
    'CT': 'Connecticut',
    'CO': 'Colorado',
    'CA': 'California',
    'AR': 'Arkansas',
    'AZ': 'Arizona'
}
